server:
  port: 19082

spring:
  application:
    name: company
  datasource:
    url: jdbc:postgresql://localhost:5432/ezmeal
    username: company_user
    password: company_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: company_service
        format_sql: true
